server:
  port: 8080

spring:
    http:
      multipart:
        max-file-size: 1000MB
        max-request-size: 10MB

    thymeleaf:
      cache: false
      mode: LEGACYHTML5

    datasource:
        url: jdbc:mysql://192.168.88.124:3306/cloudmonitor?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20